name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: false
          tags: github-languages-dashboard:1.0.0-${{ env.GITHUB_RUN_NUMBER }}

      - name: Publish Docker Image
        uses: actions/upload-artifact@v3
        with:
          name: github-languages-dashboard-1.0.0-${{ env.GITHUB_RUN_NUMBER }}
          path: github-languages-dashboard:1.0.0-${{ env.GITHUB_RUN_NUMBER }}
