name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build GitHub Pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          base_href: /github-languages-dashboard/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/github-languages-dashboard
